### ISSUE TITLE
Staticly linking with tcmalloc incurs multiple definition of `malloc/free`

### ISSUE THREAD

**Issue by amosbird** [vmarkovtsev/DeathHandler#13]
I use DeathHandler in my c++ project with tcmalloc. Building static binaries encounters this

```
gperftools-2.5/lib/libtcmalloc.a(libtcmalloc_la-tcmalloc.o): multiple definition of 'malloc'
(death_handler.cc.o): previous definition here
gperftools-2.5/lib/libtcmalloc.a(libtcmalloc_la-tcmalloc.o): multiple definition of 'free'
(death_handler.cc.o): previous definition here
```

What can I do?

**Comment by devashish2203** [comment]
@amosbird Were you able to solve this? I'm getting similar errors while using jemalloc with death handler.

**Comment by vmarkovtsev** [comment]
DeathHandler redefines malloc and free to ensure there are no allocations during stack unwinding. The easy workaround is to disable this safety arrangement and comment out anything related to that.
