### ISSUE TITLE
compile for embeeded don't show stack

### ISSUE THREAD

**Issue by bkggkt3d** [vmarkovtsev/DeathHandler#14]
It looks like DeathHandler is exactly what I need for my problem on a small ARM controller running Debian.
The development environment is on my Intel desktop PC with an chroot environment for armel to compile and link executable - usually works fine. 
But I don't see anything below "Stack trace" line in case I rsync the new binary over to my ARM controller. I've testet the sources:
`#include "death_handler.h"
  int main() {
   Debug::DeathHandler dh;
   int* p = NULL;
  *p = 0;
  return 0;
}`
made on chroot environment with
`g++ -O2 -g death_handler.cc test.cc -ldl -o test`
started with
`./test`
showing OK on chroot:
`Segmentation fault (thread 0, pid 4198)
Stack trace:
[main]
test.cc:5
0x15694 at /lib/arm-linux-gnueabi/libc.so.6
qemu: uncaught target signal 6 (Aborted) - core dumped
[1]+  Aborted                 (core dumped) ./test`
but showing NOK after rsync and exec on ARM:
`Stack trace:
[1]+  Aborted                 ./test`

I've already tried to also rsync the source file test.cc over, but still no success.
What do I need to do to see the stack trace with source-filenames and line-numbers on another machine?

Thanks
   Achim

**Comment by vmarkovtsev** [comment]
Hi.

Do you have `addr2line` binary in your `PATH` on the ARM controller? It is needed to print the trace.

**Comment by bkggkt3d** [comment]
Wow - you are great - thanks!!!!!

First I've installed the Debian package with `apt-get install binutils` than DeathHandler worked and showed source-filename and line-number.
But the full package occupied 12MB, so I've only installed the both files `/usr/bin/addr2line
/usr/lib/libbfd-2.22-system.so` which only use 660kB, now I'm happy ;-)

Thanks for this great tool and thanks for the fast help
   Achim

**Comment by vmarkovtsev** [comment]
Happy that it worked.
